### ISSUE TITLE
Cannot find json under "@nibbstack/erc721/build/"

### ISSUE THREAD

**Issue by Ryan4Work** [nibbstack/erc721#288]
Hi

After 0xcert/ethereum-erc721@2.4.0
I cannot find any json files under @nibbstack/erc721/build/.
Could you help this issue?

Thanks

**Comment by xpepermint** [comment]
You are referring to the npm, right?

**Comment by Ryan4Work** [comment]
> You are referring to the npm, right?

Yes, installed via yarn

**Comment by xpepermint** [comment]
Give me a few moments ...

**Comment by xpepermint** [comment]
Alright, I did a quick fix, so quick that I needed to skip one npm version :). Anyway, ABIs were/are there but since we switched from our own framework to hardhat, some paths changed with it. See the latest readme for details and use the latest npm (`v2.6.1`).
